version: '3'

services:
  app:
    container_name: restApi
    restart: always
    build: .

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: testMongo
    image: mongo